language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - node

os:
  - windows
  - linux
  - osx

matrix:
  allow_failures:
    - os: windows
    
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules
